[package]
name = "clipboard-history-backend"
version = "0.1.0"
description = "A Tauri App"
authors = ["Tarvi Tasane"]
edition = "2024"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
# The `_lib` suffix may seem redundant but it is necessary
# to make the lib name unique and wouldn't conflict with the bin name.
# This seems to be only an issue on Windows, see https://github.com/rust-lang/cargo/issues/8519
name = "clipboard_history_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[[bin]]
name = "clipboard-history"
path = "src/main.rs"

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon", "image-png", "devtools"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tauri-plugin-store = "2"
clipboard-rs = "0.3.4"
clipboard-history = { path = "../" }
tokio = "1.52.3"
age = "0.10"
sha2 = "0.10"
secrecy = { version = "0.8", features = ["serde"] }
base64 = "0.22"
parking_lot = "0.12"
zeroize = { version = "1", features = ["alloc"] }
rayon = "1.12.0"

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-autostart = "2"
